name: My Test Workflow

# triggers
on: [push]

# runs in parallel
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, GitHub Actions!"

    build-hello:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
          - name: Check out this repo
            uses: actions/checkout@v6

          - run: make run